-- Drop first (children before parent, because of foreign keys)
DROP TABLE IF EXISTS MAKT;
DROP TABLE IF EXISTS MARC;
DROP TABLE IF EXISTS KNA1;
DROP TABLE IF EXISTS MARA;

-- Then create (MARA first, since others reference it)
CREATE TABLE MARA (
    MATNR VARCHAR(18) PRIMARY KEY,
    MTART VARCHAR(4),
    MBRSH VARCHAR(1),
    MATKL VARCHAR(9),
    MEINS VARCHAR(3),
    NTGEW REAL,
    ERSDA VARCHAR(10)
);

CREATE TABLE MAKT (
    MATNR VARCHAR(18),
    SPRAS VARCHAR(2),
    MAKTX VARCHAR(40),
    PRIMARY KEY (MATNR, SPRAS),
    FOREIGN KEY (MATNR) REFERENCES MARA (MATNR)
);

CREATE TABLE MARC (
    MATNR VARCHAR(18),
    WERKS VARCHAR(4),
    DISMM VARCHAR(2),
    BESKZ VARCHAR(1),
    PRIMARY KEY (MATNR, WERKS),
    FOREIGN KEY (MATNR) REFERENCES MARA (MATNR)
);

CREATE TABLE KNA1 (
    KUNNR VARCHAR(10) PRIMARY KEY,
    NAME1 VARCHAR(50),
    LAND1 VARCHAR(3),
    ORT01 VARCHAR(35)
);