DROP TABLE IF EXISTS SRC_MARA;
DROP TABLE IF EXISTS SRC_MAKT;
DROP TABLE IF EXISTS SRC_MARC;
DROP TABLE IF EXISTS SRC_KNA1;

CREATE TABLE SRC_MARA (
    MATNR VARCHAR(18), MTART VARCHAR(4), MBRSH VARCHAR(1),
    MATKL VARCHAR(9), MEINS VARCHAR(3), NTGEW VARCHAR(20), ERSDA VARCHAR(10)
);
CREATE TABLE SRC_MAKT (
    MATNR VARCHAR(18), SPRAS VARCHAR(2), MAKTX VARCHAR(40)
);
CREATE TABLE SRC_MARC (
    MATNR VARCHAR(18), WERKS VARCHAR(4), DISMM VARCHAR(2), BESKZ VARCHAR(1)
);
CREATE TABLE SRC_KNA1 (
    KUNNR VARCHAR(10), NAME1 VARCHAR(50), LAND1 VARCHAR(3), ORT01 VARCHAR(35)
);